api:
  uses: python/app
  path: api
web:
  uses: node/app
  path: web
command:
  uses: go/app
  path: command
image:
  uses: docker/image
  platform: linux/amd64
  materialize:
    - from: command
      to: bin/server
chart:
  uses: helm/chart
  path: chart
  depends_on: [image]
