"""Observed AI-output evidence and explicitly conditional governance-volume models."""
def enrich(slides,ico):
    faros='https://www.faros.ai/blog/ai-software-engineering'
    latest='https://www.faros.ai/blog/ai-speed-trap-takeaways'
    github='https://github.blog/news-insights/octoverse/octoverse-a-new-developer-joins-github-every-second-as-ai-leads-typescript-to-1/'
    s=slides[2]
    s['title']='More changes. <em>More to govern.</em>'
    s['theme']='av-observed'
    s['body']='''<div class="av-evidence"><div class="av-headline"><small>MERGED PULL REQUESTS</small><strong>1.98<span>×</span></strong><h2>Nearly twice the changes.</h2><p>Faros’s 2025 enterprise telemetry study compared periods of lower and higher AI adoption within teams.</p><div class="av-sample"><b>10,000+ developers</b><span>1,255 teams · observational study</span></div></div><div class="av-bars"><small>LOWER-ADOPTION PERIOD = 100 · INDEXED METRICS</small><div class="av-bar-row"><div><b>Merged pull requests</b><strong>+98%</strong></div><div class="av-baseline" style="width:38.46%">100</div><div class="av-growth" style="width:76.15%">198</div></div><div class="av-bar-row"><div><b>Average pull-request size</b><strong>+154%</strong></div><div class="av-baseline" style="width:38.46%">100</div><div class="av-growth" style="width:97.69%">254</div></div><div class="av-bar-row av-friction"><div><b>Pull-request review time</b><strong>+91%</strong></div><div class="av-baseline" style="width:38.46%">100</div><div class="av-growth" style="width:73.46%">191</div></div><div class="av-key"><span><i></i>Lower AI adoption</span><span><i></i>Higher AI adoption</span></div></div></div><div class="av-thesis">More output enters the delivery system.<br><b>The work to verify and govern it does not disappear.</b></div>'''
    s['source']=f'<a href="{faros}">Faros AI Productivity Paradox Report, July 2025</a>. Associated changes within the study; not a causal estimate, annual growth rate or deployment forecast.'
    s['notes']='Faros methodology: telemetry across >10,000 developers/1,255 teams; compare the two quarters of lowest and two quarters of highest AI adoption for each team. Metrics company-standardized; significant Spearman associations with data from >=6 companies. Reported changes: merged PRs +98%, average PR size +154%, PR review time +91%. Indexed bars derived as 100*(1+reported percentage). Vendor observational sample, not representative population estimate or randomized experiment. Do not multiply PR count and size to claim total lines-of-code growth: aggregation and distributions are not available. No assertion all changes reach production; downstream bottlenecks are the thesis. This is a 2025 study, not a 2026 forecast; newer corroboration is in the research appendix.'
    scale=dict(label='THE GOVERNANCE MULTIPLIER',title='One release. <em>Many things to govern.</em>',theme='av-scale',subtitle='',body=f'''<div class="av-unit-flow"><div>{ico('code')}<strong>1</strong><span>eligible release candidate</span></div><i>×</i><div>{ico('package')}<strong>3</strong><span>publishable artifacts</span></div><i>×</i><div>{ico('cloud')}<strong>3</strong><span>target environments</span></div><i>=</i><div class="av-unit-total">{ico('policy')}<strong>9</strong><span>artifact–environment checks</span></div></div><div class="av-scale-lower"><div><small>ILLUSTRATIVE MONTHLY LOAD · FIXED 3 × 3 SCOPE</small><div class="av-workbar"><span>1,000 candidates</span><div><b style="width:25%"></b></div><strong>9,000</strong></div><div class="av-workbar"><span>2,000 candidates</span><div><b style="width:50%"></b></div><strong>18,000</strong></div><div class="av-workbar"><span>4,000 candidates</span><div><b style="width:100%"></b></div><strong>36,000</strong></div><div class="av-unit-caption">Potential gate evaluations, not completed deployments or security incidents.</div></div><div class="av-proof-load"><small>EACH ARTIFACT ALSO NEEDS</small><p>Identity. Checks. SBOM.<br>Provenance. Attestations.<br>Publication and deployment status.</p><b>More changes expand the governed workload—even before adding more targets or controls.</b></div></div>''',source='Oyzu scenario model, not an industry forecast. Assumes every candidate produces 3 artifacts and each is evaluated for 3 environments.',notes='Arithmetic: C candidates x A artifacts per candidate x E target environments = candidate artifact/environment gate evaluations. 1000x3x3=9000; 2000x3x3=18000; 4000x3x3=36000. Not a count of actual deployments, vulnerabilities, evidence files or attack paths. Pipeline failures, batching, retries, caching and deployment selection change actual load. Fixed scope means linear scaling with candidate volume; additional scope dimensions multiply workload. It does not prove exponential growth over time. No Faros result is used as a measured conversion factor from PRs to releases. Evidence objects can be reused across promotions; do not assume a fresh SBOM per environment.')
    slides.insert(3,scale)
    # A conditional trajectory is more honest than repackaging adoption forecasts as code volume.
    points25=[(100,390),(320,365),(540,334),(760,295)]
    points50=[(100,390),(320,340),(540,265),(760,152)]
    def poly(points):return ' '.join(f'{x},{y}' for x,y in points)
    research=dict(label='APPENDIX · OUTPUT GROWTH & PROJECTIONS',title='Observed growth. <em>Conditional futures.</em>',theme='av-research ad-appendix',subtitle='',body=f'''<div class="av-research-grid"><div class="av-current"><small>ADDITIONAL OBSERVED EVIDENCE</small><div><b>+25.1%</b><span>GitHub code pushes / commits, 2025 year over year.<br>Platform-wide activity; not all attributable to AI.</span></div><div><b>+71.8%</b><span>Average PR size in Faros’s September 2026 update.</span></div><div><b>+125.4%</b><span>Monthly incidents in that 2026 dataset.<br>More volume does not imply equal per-change risk.</span></div><p>Faros 2026: 22,000 developers, 4,000 teams. Different sample and adoption phase from the 2025 study.</p></div><div class="av-forecast"><small>IF CHANGE VOLUME GROWS AT AN ASSUMED ANNUAL RATE</small><svg viewBox="0 0 900 460" role="img" aria-label="Conditional growth paths: 25 percent a year reaches 1.95 times after three years; 50 percent reaches 3.38 times."><path class="forecast-grid" d="M100 390H780M100 290H780M100 190H780M100 90H780"/><g class="forecast-axis"><text x="55" y="398">1×</text><text x="55" y="298">2×</text><text x="55" y="198">3×</text><text x="55" y="98">4×</text><text x="87" y="432">Now</text><text x="299" y="432">+1 yr</text><text x="519" y="432">+2 yr</text><text x="739" y="432">+3 yr</text></g><polyline class="forecast-25" points="{poly(points25)}"/><polyline class="forecast-50" points="{poly(points50)}"/><text class="forecast-label label50" x="768" y="156">3.38×</text><text class="forecast-label label25" x="768" y="298">1.95×</text></svg><div class="av-forecast-key"><span>25% / year assumed</span><span>50% / year assumed</span></div><p>Volume after 3 years = baseline × (1 + annual growth)<sup>3</sup></p><b>Planning scenarios—not analyst predictions or established exponential trends.</b></div></div>''',source=f'<a href="{github}">GitHub Octoverse 2025</a> · <a href="{latest}">Faros, The Speed Trap, September 18, 2026</a>. Projection rates are selected assumptions, not extrapolated study results.',notes='GitHub reports nearly1B commits/code pushes in2025 +25.1% YoY; its page has different PR totals/baselines, so those are not combined here. Activity growth is platform-wide and includes non-enterprise/non-AI work. Faros2026 studies more intensive high-AI use over12months in22K developers/4Kteams, unlike2025 low-to-high comparisons; percentage differences are not a time series. Latest study reports average PRsize+71.8%, monthlyincidents+125.4%, incidentsperPR+14.5%; avoid implying quality worsening at earlier rates. Conditional forecast math1.25^3=1.953125;1.5^3=3.375. Rates deliberately selected for sensitivity analysis, not estimated from Faros or asserted representative annual trends. No reliable industry-wide forecast of extra enterprise production-code volume was verified in this review.')
    slides.insert(-1,research)
    sources=slides[-1]
    sources['body']=sources['body'].replace('<p><a href="https://survey.stackoverflow.co/2025/ai">Stack Overflow Developer Survey 2025</a><br>84% using or planning AI tools.</p>',f'<p><a href="{faros}">Faros AI Productivity Paradox, 2025</a> · <a href="{latest}">Speed Trap, 2026</a><br>Observed output and downstream workload.</p><p><a href="{github}">GitHub Octoverse 2025</a><br>Platform-wide code activity growth.</p>')
    return slides
