"""Editorial slide compositions. Content scopes and evidence remain in investor_narrative."""
def direct(slides, ico, tool, tag):
    # Every main slide gets a different visual job, not a repeated title + card template.
    themes=['dark ad-cover','ad-sprawl','ad-pressure','dark ad-incident','ad-model','ad-plan','ad-services','dark ad-cli','ad-record','ad-choice','ad-proof','ad-motion','ad-founder','ad-revenue','dark ad-ask']
    for s,t in zip(slides,themes):s['theme']=t

    slides[0]['title']='Software delivery.<br><em>Without the<br>pipeline burden.</em>'
    slides[0]['body']=f'''<div class="cover-orbit" aria-hidden="true"><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="orbit orbit-c"></div><div class="orbit-core">{ico('graph')}<span>OYZU</span></div><span class="orbit-tag orbit-intent">INTENT</span><span class="orbit-tag orbit-policy">POLICY</span><span class="orbit-tag orbit-proof">PROOF</span></div><div class="cover-statement"><p>Application teams declare intent.<br>Organizations define policy.<br><b>Oyzu delivers.</b></p><div class="cover-ask"><strong>$1M</strong><span>SEED ROUND<br>Source → artifact → production</span></div></div>'''
    slides[1]['title']='The hidden work<br>behind every release.'
    slides[1]['body']='<div class="sprawl-intro">A new application inherits a second project:<br><b>the machinery to build, secure and ship it.</b></div>'+slides[1]['body']

    slides[2]['title']='Code is only the beginning.'
    slides[2]['body']=f'''<div class="pressure-editorial"><div class="code-poster"><div class="code-glyph">&lt;/&gt;</div><span>CREATED</span><div class="code-gap">≠</div><b>DELIVERED</b><p>AI accelerates creation.<br>The path to production still needs an owner.</p></div><div class="delivery-stair"><small>WHAT EVERY RELEASE STILL NEEDS</small>{''.join('<div style="--step:'+str(i)+'"><span>'+str(i+1).zfill(2)+'</span>'+ico(icon)+'<b>'+title+'</b></div>' for i,(icon,title) in enumerate([('runner','Approved tools & inputs'),('check','Tests & security checks'),('evidence','Verifiable artifact evidence'),('cloud','Infrastructure & deployment')]))}<div class="stair-end">{ico('launch')}<span>Production must be repeatable,<br>governed and verifiable.</span></div></div></div><div class="pressure-source"><b>84%</b><span>of 2025 Stack Overflow respondents use or plan to use AI development tools.</span><strong>More creation makes governed delivery more valuable.</strong></div>'''

    slides[3]['title']='A dependency is compromised.'
    slides[3]['body']='<div class="incident-question">What is exposed? <span>What can ship?</span></div>'+slides[3]['body']
    slides[3]['body']=slides[3]['body'].replace('Illustrative security incident','Illustrative security incident')

    slides[4]['title']='Three responsibilities. <em>One system.</em>'
    slides[4]['body']=f'''<div class="model-verbs"><div><span class="model-number">01</span><small>APPLICATION TEAMS</small><h2>Declare<br>intent.</h2><p>Describe the application and outcome.<br>Keep native project files.</p><span class="model-example">“Deliver this service to staging.”</span></div><div><span class="model-number">02</span><small>ORGANIZATIONS</small><h2>Define<br>policy.</h2><p>Set approved tools, checks, evidence<br>and delivery conditions.</p><span class="model-example">“Only approved, verified artifacts.”</span></div><div><span class="model-number">03</span><small>OYZU</small><h2>Deliver.</h2><p>Generate the work. Execute the plan.<br>Retain proof of the outcome.</p><span class="model-example">Source → artifact → production</span></div></div><div class="model-rule">No application pipelines. <span>No pipeline templates to maintain.</span></div>'''

    slides[5]['title']='Policy becomes executable.'
    slides[5]['body']=f'''<div class="graph-inputs"><div><small>PROJECT FACTS</small><b>Node service + native lockfile</b></div><i>+</i><div><small>DECLARED INTENT</small><b>Container → staging</b></div><i>+</i><div><small>POLICY</small><b>Approved tools + required evidence</b></div></div><div class="graph-header"><span>↓ GENERATED EXECUTION PLAN</span><b>Derived per run · frozen before execution</b></div><div class="execution-graph"><svg viewBox="0 0 1200 295" preserveAspectRatio="none" aria-hidden="true"><path d="M175 140H244M412 140C450 140 434 63 480 63M412 140C450 140 434 220 480 220M655 63C700 63 690 140 734 140M655 220C700 220 690 140 734 140M910 140H985"/></svg><div class="graph-node g-source">{ico('code')}<b>Capture source</b><span>Project identity</span></div><div class="graph-node g-prepare">{ico('runner')}<b>Prepare tools<br>& inputs</b><span>Approved versions</span></div><div class="graph-node g-build">{ico('package')}<b>Build & package</b><span>Native behavior</span></div><div class="graph-node g-check">{ico('check')}<b>Tests & checks</b><span>Policy requirements</span></div><div class="graph-node g-proof">{ico('evidence')}<b>Verify evidence</b><span>Artifact-bound proof</span></div><div class="graph-node g-deliver">{ico('launch')}<b>Publish & deliver</b><span>Authorized targets</span></div></div><div class="graph-change"><span class="new-rule">+ NEW RULE</span><b>Require a license assessment</b><span class="graph-change-arrow">→</span><span>The next plan gains the assessment and its evidence gate.<br><strong>No application pipeline edit.</strong></span></div>'''
    slides[5]['source']='Conceptual dependency graph; exact ordering depends on native behavior and policy. Full managed workflow is roadmap.'

    slides[6]['title']='Security services.<br><em>Already connected.</em>'
    slides[6]['body']=f'''<div class="service-split"><div class="services-message"><span class="big-amp">&</span><p>Verifiable evidence should come<br>with the artifact.</p><strong>So should the infrastructure<br>that manages it.</strong><div class="customer-keep"><small>KEEP YOUR EXISTING</small>{tool('githubactions','CI')}{tool('jfrog','Registries')}{tool('kubernetes','Targets')}</div></div><div class="service-stack"><small>OYZU MANAGES · PRODUCT VISION</small>{''.join('<div>'+ico(icon)+'<span><b>'+title+'</b><p>'+desc+'</p></span><i>→</i></div>' for icon,title,desc in [('key','Identity & signing','Authorized identities and artifact attestations.'),('evidence','Evidence & retention','SBOMs, provenance and results tied to exact bytes.'),('policy','Verification & gates','Required evidence and current release authority.'),('clock','Audit & recovery','Status, receipts, gaps and safe retries.')])}</div></div>'''

    slides[7]['title']='One CLI.<br><em>Everywhere.</em>'
    slides[7]['body']=f'''<div class="cli-composition"><div class="cli-left"><p>One configuration interface.<br>One governed toolchain experience.</p><div class="terminal-card"><div><i></i><i></i><i></i><span>OYZU CLI</span></div><code><span>$</span> oyzu build</code><p>Install approved tools.<br>Apply policy.<br>Execute the generated plan.</p><small>COMMAND EXISTS TODAY · FULL MANAGED EXPERIENCE IS THE VISION</small></div></div><div class="cli-routes"><div class="route-trunk"></div>{''.join('<div class="cli-route">'+ico(icon)+'<span><b>'+title+'</b><small>'+desc+'</small></span></div>' for icon,title,desc in [('person','Developer machines','LOCAL TOOLS + IMMEDIATE FEEDBACK'),('agent','Cloud & AI agents','SAME COMMANDS + CONFIGURATION'),('runner','Any CI system','THIN BOOTSTRAP + GOVERNED EXECUTION')])}</div></div><div class="cli-footer"><span>Approved tools</span><i>•</i><span>Policy distribution</span><i>•</i><span>Hermetic builds*</span><i>•</i><span>Connected evidence</span></div>'''

    slides[8]['title']='The artifact is the record.'
    slides[8]['body']='<div class="record-deck">Every action. Every attestation. Every observed deployment.</div>'+slides[8]['body']

    slides[9]['title']='Who owns the machinery?'
    slides[9]['body']=f'''<div class="ownership-table"><div class="ownership-head"><span>BUYER’S CHOICE</span><span>WHAT YOU GET</span><span>WHO MAINTAINS THE DELIVERY LOGIC?</span></div><div class="ownership-row"><div><span class="choice-index">01</span><h3>Build internally</h3><small>GITHUB ACTIONS · JENKINS</small></div><p>Shared workflows and reusable automation reduce duplication.</p><div class="ownership-answer">Your platform team<span>Templates, integrations and evidence plumbing.</span></div></div><div class="ownership-row"><div><span class="choice-index">02</span><h3>Adopt a platform</h3><small>GITLAB · HARNESS</small></div><p>Integrated delivery automation and governance.</p><div class="ownership-answer">Platform + customer<span>Product conventions, workflow configuration and extensions.</span></div></div><div class="ownership-row ownership-oyzu"><div><img src="logo-color.svg" alt="Oyzu"><small>PROPOSED OPERATING MODEL</small></div><p>Intent and policy generate the supported execution plan.</p><div class="ownership-answer">Oyzu owns generation<span>You own intent, organizational rules and explicit exceptions.</span></div></div></div><div class="ownership-note"><b>Integrate first.</b> Keep existing runners, scanners and destinations.<span>Opinionated support; bounded extension hooks.</span></div>'''

    slides[10]['title']='Working code.<br><em>Real behavior.</em>'
    slides[10]['body']=f'''<div class="proof-canvas"><div class="proof-command"><small>IMPLEMENTED COMMANDS</small><code><i>$</i> oyzu build --plan</code><span>Inspect the captured-source plan</span><code><i>$</i> oyzu build</code><span>Execute supported native actions</span><code><i>$</i> oyzu inspect dist</code><span>Verify recorded content digests</span></div><div class="proof-branches"><small>DOCUMENTED NATIVE FIXTURES</small><div class="proof-branch passing"><span class="branch-mark">✓</span><div><b>Tests pass</b><p>Artifact + reports retained</p></div><div class="branch-output">{ico('package')}<span>OUTPUT</span></div></div><div class="proof-branch failing"><span class="branch-mark">×</span><div><b>Assertion or coverage fails</b><p>Failure evidence retained</p></div><div class="branch-output">{ico('policy')}<span>NO ARTIFACT</span></div></div><div class="digest-proof"><b>=</b><span>Repeated qualified Yarn builds<br><strong>Identical archive digests</strong></span></div></div></div><div class="proof-next"><span>NEXT</span><p>Managed policy, evidence services and governed publication.</p><a href="https://github.com/micahlmartin/oyzu/actions/runs/36863353630">Inspect the historical CI evidence →</a></div>'''

    slides[11]['title']='One mandate.<br><em>An organization-wide opportunity.</em>'
    slides[11]['body']=f'''<div class="adoption-bridge"><div class="bridge-stage bridge-one"><span>01</span><small>REACH</small><h3>Find the<br>mandate.</h3><p>Founder-led outreach to platform leaders facing a runtime upgrade or evidence requirement.</p><b>Named sponsor</b></div><div class="bridge-stage bridge-two"><span>02</span><small>LAND</small><h3>Prove the<br>workflow.</h3><p>Real repositories. Existing CI. Measure setup effort, policy changes and evidence retrieval.</p><b>Accepted evaluation</b></div><div class="bridge-stage bridge-three"><span>03</span><small>EXPAND</small><h3>Govern<br>the estate.</h3><p>Extend shared authority to more teams, repositories and evidence-retention needs.</p><b>Paid organizational adoption</b></div></div><div class="buyer-caption"><span>INITIAL BUYER</span><b>Head of Platform Engineering / DevSecOps</b><p>Multiple application teams. Mixed CI. Recurring mandates.</p></div>'''

    slides[12]['title']='Built for this problem.'
    slides[12]['body']=f'''<div class="founder-editorial"><div class="founder-identity"><div class="founder-years"><b>20</b><span>YEARS BUILDING<br>DEVELOPER INFRASTRUCTURE</span></div><h2>Micah Martin</h2><p>Founder · Platform engineering leader<br>Entrepreneur across startups and investments</p></div><div class="founder-credentials"><div><span>BUILD</span><h3>Engineering & DevOps leadership</h3><p>Lifion by ADP · Engineering Manager, DevOps<br>SoulCycle · Director of Engineering</p></div><div><span>GOVERN</span><h3>Enterprise operating experience</h3><p>Current AVP, Platform Engineering<br>at a major enterprise</p></div><div><span>SELL</span><h3>Customer-facing delivery expertise</h3><p>Harness · Solutions Architecture → Director<br>2020-2024</p></div></div></div>'''

    slides[13]['title']='Adoption earns trust.<br><em>Governance earns revenue.</em>'
    slides[13]['body']=f'''<div class="revenue-stair"><div class="revenue-entry"><span class="money-zero">FREE</span><small>REPOSITORY-LEVEL ADOPTION</small><p>Bounded hosted policy and evidence.<br>Start on existing CI.</p></div><div class="revenue-core"><span class="money-symbol">$</span><div><small>CORE RECURRING REVENUE</small><h2>Organizational<br>subscription</h2><p>Cross-repository policy · tool controls<br>Roles · exceptions · credential authority</p></div></div><div class="revenue-usage"><span class="money-plus">+</span><small>USAGE EXPANSION</small><h3>Retention<br>& storage</h3><p>More governed teams.<br>More retained evidence.</p></div></div><div class="revenue-axis"><span>PROJECT VALUE</span><div></div><span>ORGANIZATIONAL VALUE →</span></div><div class="revenue-later"><b>Existing execution first.</b><span>Optional Oyzu compute becomes a separate usage business later.</span><small>COMMERCIAL MODEL · NOT A REVENUE FORECAST</small></div>'''

    slides[14]['title']='$1M'
    # SVG chart proportions represent the actual proposed 60/25/15 budget, not business results.
    slides[14]['body']=f'''<div class="ask-tagline">To make governed delivery<br><em>a repeatable enterprise product.</em></div><div class="ask-allocation"><div class="allocation-ring"><svg viewBox="0 0 220 220" aria-label="Proposed allocation: 60 percent product, 25 percent customer validation, 15 percent operations"><circle class="ring-base" cx="110" cy="110" r="85"/><circle cx="110" cy="110" r="85" pathLength="100" stroke="#bccf9c" stroke-dasharray="60 40" stroke-dashoffset="0"/><circle cx="110" cy="110" r="85" pathLength="100" stroke="#d8a777" stroke-dasharray="25 75" stroke-dashoffset="-60"/><circle cx="110" cy="110" r="85" pathLength="100" stroke="#72877a" stroke-dasharray="15 85" stroke-dashoffset="-85"/></svg><span>12<small>MONTH PLAN</small></span></div><div class="allocation-legend"><div><i style="background:#bccf9c"></i><strong>$600K</strong><span>Product & engineering</span></div><div><i style="background:#d8a777"></i><strong>$250K</strong><span>Customer validation & onboarding</span></div><div><i style="background:#72877a"></i><strong>$150K</strong><span>Operations & reserve</span></div></div></div><div class="ask-targets"><div><b>3</b><span>Design partners</span></div><div><b>6</b><span>Independent repositories<br>across ≥2 CI systems</span></div><div><b>2</b><span>Paying organizations</span></div></div><div class="ask-target-label">PROPOSED EXIT TARGETS · ONBOARDING ≤ 1 ENGINEER-DAY PER SUPPORTED PROJECT</div>'''

    # Appendix remains useful, with shorter headings and its own visual register.
    appendix_titles=['The connected ecosystem.','Inside the native build evidence.','What repeated delivery work can cost.','How the $1M is allocated.','Prior art & integration opportunities.','Sources, scope & assumptions.']
    for s,title in zip(slides[15:],appendix_titles):
        s['title']=title;s['theme']='ad-appendix'
    slides[17]['theme']='ad-appendix ad-economics'
    return slides
