import re

def finish(slides):
    radar='''<div class="journey-radar"><svg viewBox="0 0 560 590" role="img" aria-label="Oyzu governs a verified path from source through artifacts to production"><defs><radialGradient id="radarGlow"><stop stop-color="#9bb97e" stop-opacity=".16"/><stop offset="1" stop-color="#9bb97e" stop-opacity="0"/></radialGradient></defs><circle cx="275" cy="285" r="250" fill="url(#radarGlow)"/><g class="radar-grid"><circle cx="275" cy="285" r="235"/><circle cx="275" cy="285" r="165"/><circle cx="275" cy="285" r="95"/><path d="M25 285H525M275 35V535"/></g><path class="radar-sector" d="M275 285L455 134A235 235 0 0 0 392 82Z"/><g class="radar-ring-label"><text x="83" y="433">PRODUCTION</text><text x="153" y="388">ARTIFACTS</text><text x="207" y="350">SOURCE</text></g><path class="radar-route" d="M275 285L348 224L401 179L455 134"/><g class="radar-check"><circle cx="348" cy="224" r="12"/><circle cx="401" cy="179" r="12"/><circle cx="455" cy="134" r="12"/><path d="m343 224 4 4 7-8m42-41 4 4 7-8m42-41 4 4 7-8"/></g><g class="radar-verified"><text x="365" y="244">VERIFIED</text><text x="418" y="199">VERIFIED</text><text x="472" y="154">VERIFIED</text></g><circle class="radar-core" cx="275" cy="285" r="53"/><image href="logo.svg" x="236" y="273" width="78" height="24"/><g class="radar-logos"><image href="tool-logos/gitlab.svg" x="181" y="230" width="26" height="26"/><image href="tool-logos/githubactions.svg" x="256" y="196" width="25" height="25"/><image href="tool-logos/docker.svg" x="110" y="274" width="32" height="32"/><image href="tool-logos/jfrog.svg" x="241" y="117" width="28" height="28"/><image href="tool-logos/aws.svg" x="65" y="148" width="35" height="35"/><image href="tool-logos/azure.svg" x="264" y="44" width="30" height="30"/><image href="tool-logos/googlecloud.svg" x="458" y="369" width="32" height="32"/><image href="tool-logos/kubernetes.svg" x="298" y="500" width="31" height="31"/></g><text class="radar-caption" x="275" y="577" text-anchor="middle">ONE GOVERNED PATH · SOURCE TO PRODUCTION</text></svg></div>'''
    slides[0]['body']=re.sub(r'<div class="cover-orbit".*?(?=<div class="cover-statement">)',radar,slides[0]['body'],flags=re.S)
    slides[0]['notes']+=' Radar depicts the product model, not a live telemetry dashboard. Verified markers illustrate required gates, not actual successful releases. Logos identify intended ecosystem touchpoints.'
    s=next(s for s in slides if s['label']=='FOUNDER FIT')
    s['label']='THE FOUNDING TEAM';s['theme']='ft-team'
    s['body']='''<div class="ft-main"><div class="ft-profile"><img src="founder-micah.jpg" alt="Micah Martin"><div><small>FOUNDER</small><h2>Micah Martin</h2><p>Platform engineering leader.<br>Entrepreneur. Builder.</p><div class="ft-years"><b>20</b><span>YEARS BUILDING<br>DEVELOPER INFRASTRUCTURE</span></div></div></div><div class="ft-career"><div><small>BUILD</small><h3>Engineering & DevOps leadership</h3><p>Lifion by ADP · Engineering Manager, DevOps<br>SoulCycle · Director of Engineering</p></div><div><small>GOVERN</small><h3>Enterprise operating experience</h3><p>Current AVP, Platform Engineering · major enterprise</p></div><div><small>SELL</small><h3>Customer-facing delivery expertise</h3><p>Harness · Solutions Architecture → Director · 2020-2024</p></div></div></div><div class="ft-future"><small>ADDITIONAL COFOUNDERS · DETAILS TO FOLLOW</small><div class="ft-slots">'''+''.join('<div><span class="ft-avatar">+</span><span><b>Cofounder '+str(i)+'</b><small>Name · role · background to come</small></span></div>' for i in range(2,5))+'''</div></div>'''
    s['source']='Role history: founder-provided LinkedIn screenshots. Career duration and entrepreneurship: founder-provided. Photo: GitHub @micahlmartin. Additional profiles are placeholders.'
    s['notes']+=' Three additional profiles are placeholders, not assertions of confirmed individuals or commitments. Photo: https://github.com/micahlmartin.png.'
    return slides
