def strengthen(slides):
    def find(label):return next(s for s in slides if s['label']==label)
    cli=find('ONE GOVERNED DEVELOPER EXPERIENCE')
    cli['title']='Governance starts<br><em>where code starts.</em>'
    cli['theme']='es-local'
    cli['body']='''<div class="es-late"><small>WHEN CONTROLS ARRIVE ONLY IN CI</small><div><span>Choose tools</span><i>→</i><span>Build the feature</span><i>→</i><b>CI rejects the runtime</b></div><p>Now the team faces rework, exception requests and another approval queue.</p></div><div class="es-local-grid"><div><small>THE OYZU EXPERIENCE</small><h2>Make the approved path<br>the easy path.</h2><p>One CLI and configuration interface for developers, cloud agents and existing CI.</p><div class="es-toolset"><img src="tool-logos/nodedotjs.svg" alt="Node.js"><img src="tool-logos/python.svg" alt="Python"><img src="tool-logos/go.svg" alt="Go"><img src="tool-logos/rust.svg" alt="Rust"></div></div><div class="es-session"><small>ILLUSTRATIVE TOOL REQUEST</small><div><span>REQUEST</span><b>Use this project’s toolchain</b></div><div><span>RESOLVE</span><b>Select a policy-approved version</b></div><div><span>PREPARE</span><b>Install from a trusted source</b></div><div><span>AUTHORIZE</span><b>Provide scoped dependency access</b></div><p>A conflict is explained before work builds on it.</p></div></div>'''
    cli['source']='Illustrative governed workflow. Controls apply to Oyzu-managed paths; broader endpoint enforcement requires additional controls. Implemented scope appears on the working-foundation slide.'
    cli['notes']='The local agent, shims, tool identity and credential authority are part of the integrated design. Do not imply shims prevent arbitrary binaries outside managed paths. Approved version resolution must respect project compatibility or explain conflicts, not silently force upgrades. The same policy can have explicit context-specific rules. Diagram is illustrative, not a literal implemented command transcript.'
    managed=find('MANAGED ARTIFACT SECURITY')
    managed['title']='One policy.<br><em>From first install to production.</em>'
    managed['theme']='es-connected'
    stages=[('01','Workstation','Approved tools<br>Trusted dependencies','nodedotjs'),('02','Cloud agents','Same interface<br>Scoped authority','githubactions'),('03','CI','Generated plan<br>Required checks','gitlab'),('04','Artifact','SBOM + provenance<br>Signed attestations','docker'),('05','Production','Authorized delivery<br>Observed status','kubernetes')]
    managed['body']='''<div class="es-policy-rail"><span>ORGANIZATIONAL POLICY</span><b>Tools · dependency sources · checks · evidence · delivery conditions</b></div><div class="es-stage-row">'''+''.join('<div><small>'+n+'</small><img src="tool-logos/'+logo+'.svg" alt=""><h3>'+title+'</h3><p>'+desc+'</p></div>' for n,title,desc,logo in stages)+'''</div><div class="es-evidence-rail"><b>ONE CONNECTED EVIDENCE TRAIL</b><span>Identity → action → tool version → result → artifact digest → deployment</span></div><div class="es-managed"><strong>The integration is the product.</strong><p>Oyzu manages policy distribution, credential coordination, evidence retention and verification.<br>Customers keep their existing execution and delivery infrastructure.</p></div>'''
    managed['source']='Architecture illustration; logos show ecosystem examples, not endorsements. Evidence records observed activity and identifies missing coverage.'
    managed['notes']='Full connected product architecture, not an assertion all components are shipped. Working-foundation and funding slides define implementation scope. Managed services remove customer integration and evidence-infrastructure work for supported paths; existing CI, registries, scanners and deployment systems still have operational costs. Cloud-agent logo represents an execution ecosystem, not a partnership or an AI model. Same governing policy may resolve different requirements by context.'
    # Local feedback precedes the connected-system architecture.
    local_index=slides.index(cli);managed_index=slides.index(managed)
    slides[managed_index],slides[local_index]=cli,managed
    model=find('THE OPERATING MODEL')
    model['body']=model['body'].replace('No application pipelines. <span>No pipeline templates to maintain.</span>','Delivery expertise is built in. <span>The enterprise stays in control.</span>')
    plan=find('HOW THE PLAN IS GENERATED')
    plan['notes']+=' Opinionated supported stack profiles own execution mechanics; policy specifies requirements rather than procedural steps. Native project configuration and explicit exceptions remain. Avoid turning policy into a replacement pipeline language.'
    comp=find('THE COMPETITIVE DIVIDE')
    comp['body']=comp['body'].replace('Opinionated local-to-CI experience; product-owned workflow generation','Governed tools from the workstation; product-owned delivery and connected evidence')
    together=find('COMPETE ON THE MODEL · INTEGRATE ON ADOPTION')
    together['body']=together['body'].replace('Generate the required work. Govern the tools. Connect the evidence.','Govern the first install. Generate delivery. Retain the proof.')
    ai=dict(label='THE AI OBJECTION',title='AI can write the pipeline.<br><em>Why should you need one?</em>',theme='es-ai',subtitle='',body='''<div class="es-ai-paths"><div class="es-ai-old"><small>AI-ASSISTED PIPELINE AUTHORING</small><h2>Faster to create.<br>Still yours to own.</h2><div class="es-code">prompt → workflow code</div><p>Review and validate the output.<br>Maintain tools and integrations.<br>Roll out requirements and collect evidence.</p></div><div class="es-ai-new"><small>THE OYZU MODEL</small><h2>Declare intent.<br>The delivery expertise is built in.</h2><div class="es-contract"><span>INTENT</span><i>+</i><span>POLICY</span><i>→</i><b>PLAN + PROOF</b></div><p>An opinionated, maintained path for each supported stack.<br>Oyzu owns generation and execution mechanics.<br>The enterprise owns requirements and exceptions.</p></div></div><div class="es-ai-close"><strong>AI accelerates creation. Oyzu governs execution.</strong><span>Agents can declare intent and propose changes. Policy, authorization and evidence still apply.</span></div>''',source='Operating-model distinction, not a claim that AI cannot govern workflows or that every competitor uses the same approach.',notes='AI can assist authoring, maintenance, policy and remediation; it does not inherently establish trusted authority or eliminate ownership obligations. This compares AI-assisted pipeline authoring with Oyzu’s product responsibility, not a claim of current specific AI features in Harness/GitLab. Competitors can evolve toward this model. Validate differentiation through customer maintenance effort, supported coverage and exception burden. One maintained path per supported stack does not mean all applications have identical tests, outputs or packaging. Do not imply stochastic model output is trusted without validation; execution requirements remain explicit and auditable.')
    ai['title']='“Can’t AI just<br><em>write the pipelines?”</em>'
    ai['theme']='es-objection'
    ai['body']='''<div class="ob-answer"><small>THE SHORT ANSWER</small><h2>Writing it is only the beginning of owning it.</h2><p>AI can help create and maintain a pipeline. The customer still owns the workflow and its obligations.</p></div><div class="ob-obligations"><span>Validate</span><span>Update</span><span>Govern</span><span>Integrate</span><span>Collect evidence</span></div><div class="ob-oyzu"><small>WHAT OYZU REMOVES</small><h2>The application pipeline<br>your team has to own.</h2><p>Teams declare intent. Organizations define policy.<br>Delivery expertise is built into the product.</p><div class="ob-close">No application pipelines to author. No pipeline templates to maintain.</div></div>'''
    ai['source']='Oyzu generates execution plans directly from intent, native project configuration and policy. AI-generated pipeline code is not the Oyzu model.'
    ai['notes']='Investor objection and response, not a comparison between vendors or an AI feature pitch. AI can assist both authoring and ongoing maintenance; that does not inherently transfer workflow ownership to a product. Oyzu owns the supported delivery mechanics and derives per-run execution plans without customer-authored application pipelines or templates. Customers retain intent, native project configuration, organizational requirements and explicit exceptions. Existing CI may retain a thin bootstrap. No claim that all automation or execution graphs disappear.'
    slides.insert(3,ai)
    return slides
