"""Investor-facing language, clear maturity framing, and unified appendix."""
import re
from competitor_comparisons import expand_comparisons


def polish(slides, ico):
    by = {s['label']: s for s in slides}
    replacements = {
        'THE OPERATING MODEL': [('The intended operating model.', 'The steps still exist.'), ('The enterprise stays in control.', 'Oyzu generates and maintains them.')],
        'HOW THE PLAN IS GENERATED': [('INTENDED EXECUTION PLAN', 'GENERATED EXECUTION PLAN')],
        'ONE GOVERNED DEVELOPER EXPERIENCE': [('INTENDED OYZU EXPERIENCE', 'THE APPROVED PATH'), ('AT EACH MANAGED INVOCATION', 'FROM THE FIRST COMMAND')],
        'ORGANIZATIONAL CHANGE MANAGEMENT': [('PLANNED ROLLOUT MODEL', 'ONE SHARED REQUIREMENT')],
        'MANAGED ARTIFACT SECURITY': [('TARGET ARCHITECTURE · ORGANIZATIONAL POLICY', 'ORGANIZATIONAL POLICY')],
        'THE UNIFIED AUDIT TRAIL': [('CONCEPT RECORD', 'PRODUCT CONCEPT'), ('ACTIONS & OBSERVED STATUS · ILLUSTRATIVE', 'ACTIONS & OBSERVED STATUS')],
        'COMPETE ON THE MODEL · INTEGRATE ON ADOPTION': [('PLANNED INTEGRATIONS · INTENT + POLICY', 'INTEGRATION ROADMAP'), ('Better together, early', 'Adopt alongside existing tools'), ('Who owns application delivery logic, governance and the associated platform budget.', 'Oyzu owns delivery logic and governance; existing platforms can provide execution.')],
        'THE FIRST CUSTOMER': [('Accepted evaluation', 'Pilot success criteria met')],
        'THE BUSINESS MODEL': [('Bounded hosted policy and evidence.', 'Hosted policy and evidence with usage limits.'), ('COMMERCIAL MODEL · NOT A REVENUE FORECAST', 'SUBSCRIPTION + USAGE')],
        'APPENDIX · ENGINEERING EVIDENCE': [('qualified destination adapters', 'tested publication integrations'), ('Public implementation evidence establishes selected technical behavior. Customer adoption and full conformance remain to be earned.', 'Next milestone: publish artifacts through centrally governed policy and evidence services.')],
        'APPENDIX · ECONOMIC SENSITIVITY': [('Validate the savings against onboarding, subscription, exceptions and operating costs.', 'Net value includes onboarding, subscription and ongoing operating costs.'), ('Measure net value in customer deployments.', 'Example assumptions: four hours per repository at $100 per hour.')],
        'APPENDIX · OPERATING PLAN': [('WHAT COUNTS AS PROGRESS', '12-MONTH TARGETS'), ('Two paid organizational subscriptions after an accepted evaluation; no current commitments implied.', 'Convert two successful pilots into paid organizational subscriptions.')],
        'APPENDIX · COMPLIANCE ECONOMICS': [('Customer-validation model, not a survey result or Oyzu savings claim.', 'Example assumptions for a single annual audit cycle.'), ('No universal “failed audit” dollar figure is asserted.', ''), ('Measure with design partners', 'Pilot measurement'), ('Keep failure costs separate', 'Additional cost drivers')],
    }
    for label, pairs in replacements.items():
        for old, new in pairs:
            by[label]['body'] = by[label]['body'].replace(old, new)
    # One clear maturity statement introduces the solution sequence.
    for label, subtitle in [('ONE GOVERNED DEVELOPER EXPERIENCE', 'Developer friction'), ('ORGANIZATIONAL CHANGE MANAGEMENT', 'Rollout burden'), ('MANAGED ARTIFACT SECURITY', 'Fragmented evidence')]:
        by[label]['label'] = subtitle.upper() + ' · THE OYZU MODEL'
    team = by['THE FOUNDING TEAM']
    team['body'] = team['body'].split('<div class="ft-future">')[0]
    team['title'] = 'Built for this problem.'
    foundation = by['THE WORKING FOUNDATION']
    foundation['theme'] = 'ip-foundation'
    foundation['body'] = '<div class="ip-three"><div><small>WORKING TODAY</small><h2>Native builds.<br>Retained evidence.</h2><p>The CLI plans and runs supported native builds, retaining artifacts, test reports and failure records.</p><a href="https://github.com/micahlmartin/oyzu/actions/runs/36863353630">View build verification</a></div><div><small>THIS ROUND</small><h2>Governed<br>publication.</h2><p>Central policy, organizational identity, evidence services and publication gates.</p></div><div><small>THEN</small><h2>Broader<br>delivery.</h2><p>Extend the same governance and evidence model across more deployment destinations.</p></div></div><div class="takeaway">A working build foundation. A focused path to enterprise delivery.</div>'
    research = by['APPENDIX · OUTPUT GROWTH & PROJECTIONS']
    research['label'] = 'APPENDIX · AI & SOFTWARE VOLUME'
    research['title'] = 'More software.<br><em>More downstream pressure.</em>'
    research['theme'] = 'ip-research'
    research['body'] = '<div class="ip-three"><div><small>GITHUB · 2025</small><h2>+25.1%</h2><h3>Code activity</h3><p>Year-over-year growth in code pushes / commits across GitHub.</p></div><div><small>FAROS · 2026</small><h2>+71.8%</h2><h3>Average PR size</h3><p>Larger changes in the study’s higher-AI-adoption periods.</p></div><div><small>FAROS · 2026</small><h2>+125.4%</h2><h3>Monthly incidents</h3><p>More incident volume in the same dataset.</p></div></div><div class="takeaway">Separate studies, consistent pressure on downstream systems.</div><p>GitHub measures platform-wide activity. Faros covers 22,000 developers across 4,000 teams; its 2026 sample differs from the 2025 study.</p>'
    sources = by['APPENDIX · SOURCES & BOUNDARIES']
    sources['title'] = 'References.'
    sources['label'] = 'APPENDIX · REFERENCES'
    sources['body'] = sources['body'].replace('Founder-provided LinkedIn screenshots', 'Micah Martin’s career history').replace('Listed role titles and chronology; no employer endorsement.', 'Platform engineering, enterprise governance and customer-facing delivery.').replace('Concept boards, budget targets and illustrative economics are labeled. Third-party logos identify intended ecosystem surfaces.', '')
    sources['body'] = sources['body'].replace('<h3>Industry & prior art</h3>', '<h3>Industry & prior art</h3><p><a href="https://www.harness.io/the-state-of-software-engineering-excellence">Harness Engineering Excellence 2025</a> · <a href="https://www.atlassian.com/blog/developer/developer-experience-report-2025">Atlassian Developer Experience 2025</a><br>Environment readiness and organizational friction.</p>')
    sources['body'] = re.sub(r'<p>Concept boards,.*?</p>', '', sources['body'], flags=re.S)
    sources['body'] = sources['body'].replace('<h3>Product & founder evidence</h3>', '<h3>Product &amp; research evidence</h3><p><a href="https://8588479.fs1.hubspotusercontent-na1.net/hubfs/8588479/State%20of%20Trust%20Report%20-%20October%202025.pdf">Vanta State of Trust 2025</a><br>Reported compliance workload.</p>')
    divider = dict(label='APPENDIX', title='Appendix', body='<p>Product evidence. Economics. Operating plan. References.</p>', theme='dark ip-divider', subtitle='', source='', notes='Supporting detail for investor review and questions.')
    slides.insert(20, divider)
    plan = by['HOW THE PLAN IS GENERATED']
    plan['title'] = 'Defined centrally. <em>Executed by the CLI.</em>'
    plan['theme'] = 'policy-execution'
    plan['title'] = 'Your CI provides compute. <em>Oyzu determines the work.</em>'
    plan['body'] = f'''<div class="pf-diagram">
    <svg class="pf-lines" viewBox="0 0 1280 540" aria-hidden="true"><defs><marker id="pf-arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="none" stroke="#819574" stroke-width="1.5"/></marker></defs><g fill="none" stroke="#819574" stroke-width="2.5" marker-end="url(#pf-arrow)"><path d="M235 170C310 170 300 230 375 230"/><path d="M235 370C310 370 300 270 375 270"/><path d="M510 250H560"/><path d="M652 250H680"/><path d="M762 250H790"/><path d="M885 250H915"/><path d="M1000 250H1080"/></g><path d="M330 440H1040" stroke="#cbd0c7" stroke-width="1.5"/></svg>
    <div class="pf-policy">{ico('cloud')}<h2>Central policy</h2><p>Approved tools<br>Required checks<br>Publication rules</p><span class="pf-new">+ Require license check</span></div>
    <div class="pf-app">{ico('code')}<h2>Application</h2><p>Intent + project facts</p></div>
    <div class="pf-runtime"><span>OYZU EXECUTION · PLAN RESOLVED FOR EACH RUN</span></div>
    <div class="pf-cli">{ico('code')}<h2>Oyzu CLI</h2><p>Fetch policy<br>Generate plan</p></div>
    <div class="pf-step pf-build">{ico('package')}<b>Build</b></div>
    <div class="pf-step pf-scan">{ico('policy')}<b>Scan</b></div>
    <div class="pf-step pf-license">{ico('check')}<b>License<br>check</b><small>NEW POLICY STEP</small></div>
    <div class="pf-step pf-publish">{ico('launch')}<b>Publish</b></div>
    <div class="pf-output">{ico('package')}<h2>Artifact</h2><p>{ico('evidence')} Attached evidence</p></div>
    <div class="pf-hosts"><small>RUNS ON YOUR COMPUTE</small><span>{ico('runner')}Local / runner</span><span><img src="tool-logos/githubactions.svg" alt="">GitHub Actions</span><span><img src="tool-logos/gitlab.svg" alt="">GitLab</span><span><img src="tool-logos/harness.svg" alt="">Harness</span><span><img src="tool-logos/jenkins.svg" alt="">Jenkins</span></div>
    </div><div class="pf-bottom">A new policy adds a check to the next applicable plan.<br><strong>No application pipeline or vendor-specific template to rewrite.</strong></div>'''
    plan['notes'] += ' Conceptual operating flow. Central policy expresses requirements, not a manually authored sequence. The CLI fetches applicable policy and combines it with application intent, project facts and supported integration logic, then executes a resolved plan. New integration support remains product engineering work. Current implementation scope is presented separately on the working foundation slide.'
    local = by['ONE GOVERNED DEVELOPER EXPERIENCE']
    local['title'] = 'Same CLI. Same policy system.<br><em>The right checks for the task.</em>'
    local['theme'] = 'local-paths'
    def task_path(kind, icon, title, steps, outcome):
        return '<div class="lp-lane '+kind+'"><div class="lp-label">'+ico(icon)+'<h2>'+title+'</h2></div><div class="lp-steps">'+'<i>→</i>'.join('<span>'+step+'</span>' for step in steps)+'</div><div class="lp-outcome">'+outcome+'</div></div>'
    local['body'] = '<div class="lp-inputs"><div>'+ico('cloud')+'<span>Organizational policy</span></div><b>+</b><div>'+ico('code')+'<span>Application + task intent</span></div><b>→</b><div class="lp-cli">'+ico('runner')+'<strong>Oyzu CLI</strong><span>Resolves the applicable plan</span></div></div><p class="lp-caption">Example plans selected by task and policy</p><div class="lp-paths">'+task_path('lp-fast','code','Local fast check',['Format checks','Targeted build + tests','Selected scans'],'Fast feedback<br><strong>No publication</strong>')+task_path('lp-snapshot','package','Snapshot candidate',['Build + tests','Coverage','Required scans','Publish snapshot'],'Development<br><strong>artifact + evidence</strong>')+task_path('lp-release','launch','Release',['Build + full checks','Security + license gates','Verify evidence','Approved publication'],'Release<br><strong>artifact + evidence</strong>')+'</div><div class="lp-takeaway">One governed toolchain. Short feedback loops locally. Required gates before publication.</div>'
    local['source'] = ''
    local['notes'] += ' Example plans, not fixed product commands or universal exclusions. Applicable policy determines scan, license, test and coverage requirements. Local work can require additional checks. Fast-check intent does not publish; snapshot and release intent use their applicable publication gates. The same CLI and policy model resolve each plan. Current implementation scope remains on the working foundation slide.'
    slides.remove(local)
    slides.insert(slides.index(plan) + 1, local)
    extension_body = '<div class="ex-policy">'+ico('policy')+'<span>Policy governs approved capabilities, execution gates and retained evidence.</span></div><div class="ex-label">PLUGINS PARTICIPATE IN THE WORK</div><div class="ex-plugins">'+''.join('<div>'+ico(icon)+'<h2>'+title+'</h2><p>'+example+'</p></div>' for icon,title,example in [('package','Build','Internal build system'),('policy','Scan','Proprietary security service'),('check','Gate','External approval API'),('launch','Publish','Internal registry or destination')])+'</div><div class="ex-join" aria-hidden="true"><svg viewBox="0 0 1200 48" preserveAspectRatio="none"><path d="M140 0V20H1060V0M447 0V20M753 0V20M600 20V45m-6-6 6 6 6-6"/></svg></div><div class="ex-path"><strong>OYZU CLI</strong><span>Executes the governed plan</span></div><div class="ex-event-link"><span>Lifecycle events / webhooks</span></div><div class="ex-branch" aria-hidden="true"><svg viewBox="0 0 1200 40"><path d="M600 0V16M190 37V16H1010V37M600 16V37m-6-6 6 6 6-6M184 31l6 6 6-6M1004 31l6 6 6-6"/></svg></div><div class="ex-events">'+''.join('<div>'+ico(icon)+'<span><strong>'+title+'</strong><small>'+example+'</small></span></div>' for icon,title,example in [('person','Notify teams','A required check fails'),('graph','Update work tracking','An artifact is published'),('evidence','Connect audit systems','Evidence becomes available')])+'</div><div class="ex-takeaway">Extend what runs. Connect what happens. Keep policy in control.</div>'
    slides.insert(slides.index(local) + 1, dict(label='EXTENSIBILITY', title='Opinionated execution.<br><em>Extensible integrations.</em>', body=extension_body, theme='extension-model', subtitle='', source='', notes='Product architecture concept, with illustrative extension categories rather than accepted plugin contracts. Plugins participate in governed execution; events and webhooks notify surrounding systems. Blocking approvals must be modeled as gates, not assumed from asynchronous notification delivery. Exact APIs, event semantics, permissions and compatibility contracts require design. Current implementation scope is recorded separately on the foundation slide.'))
    cli_example = dict(label='APPENDIX · LOCAL DEVELOPER EXPERIENCE', title='Any stack.<br><em>Same command.</em>', theme='cli-example', subtitle='', source='',
        body='<div class="ce-layout"><div class="ce-terminal"><div class="ce-terminal-head">LOCAL TERMINAL · IN YOUR PROJECT</div><section><small>01 · PREVIEW</small><code><span>$</span> oyzu build --plan</code><p>Inspect the plan before executing build actions.</p></section><section><small>02 · BUILD</small><code><span>$</span> oyzu build</code><p>Run supported native build actions.</p></section><section><small>03 · SCAN</small><code><span>$</span> oyzu scan</code><p>Run applicable security checks and retain findings.</p></section><section><small>04 · PUBLISH WHEN READY</small><code><span>$</span> oyzu publish</code><p>Infer the build output, verify it, and authorize publication.</p></section></div><div class="ce-story"><h2>Every project starts with<br><code>oyzu build</code>.</h2><p>Oyzu detects the stack and runs the right native tools. Developers use the same command across projects.</p><div>'+ico('package')+'<span><strong>Successful build</strong>Artifact and reports retained.</span></div><div>'+ico('evidence')+'<span><strong>Failed test or coverage gate</strong>Failure evidence retained for diagnosis.</span></div><p class="ce-close">Local builds give feedback. Publication applies the required authorization and evidence checks.</p></div></div>',
        notes='Product workflow illustration, not a captured terminal run. build and build --plan are documented CLI commands; scan is a founder-directed product command illustration, not a verified implemented command; publish uses founder-directed inferred build output, refining the explicit bundle argument in the existing OEP-0013 draft; it is not claimed as implemented here. No output transcript or fresh product execution is implied. Build behavior depends on supported ecosystems and provisioned tools. Publication verifies the bundle and current authorization; it is an explicit follow-on action, not part of the local fast-check path. Success and failure examples reflect documented native test fixtures. See docs/reference/README.md and docs/implementation-status.md.')
    appendix_index = next(i for i, slide in enumerate(slides) if slide['label'] == 'APPENDIX')
    slides.insert(appendix_index + 1, cli_example)
    pressure = by['WHY NOW']
    pressure['title'] = 'AI accelerates code creation.<br><em>Enterprise delivery must keep pace.</em>'
    pressure['theme'] = 'pressure-overview'
    pressure['body'] = '<div class="po-layout"><div class="po-volume"><small>WITH HIGHER AI ADOPTION</small><h2><span class="po-rise" aria-hidden="true"><svg viewBox="0 0 32 44"><path d="M16 0 32 17H23V44H9V17H0Z" fill="currentColor"/></svg></span>98%</h2><p>more merged pull requests</p><h2><span class="po-rise" aria-hidden="true"><svg viewBox="0 0 32 44"><path d="M16 0 32 17H23V44H9V17H0Z" fill="currentColor"/></svg></span>154%</h2><p>larger pull requests on average</p><div class="po-security-input"><strong>New vulnerabilities.</strong><span>New controls.<br>New scanning requirements.</span></div></div><div class="po-arrow" aria-hidden="true">→</div><div class="po-bottlenecks"><small>EXISTING ENTERPRISE BOTTLENECKS</small>'+''.join('<div>'+ico(icon)+'<span><strong>'+title+'</strong><p>'+copy+'</p></span></div>' for icon,title,copy in [('code','Developer setup','Find approved tools. Resolve environment gaps.'),('graph','Organizational rollout','Update workflows. Coordinate adoption.'),('evidence','Security and evidence','Trace exposure. Prove controls ran.')])+'</div><div class="po-arrow" aria-hidden="true">→</div><div class="po-impact po-consequences"><small>PRESSURE ON DELIVERY</small><div><strong>Changes wait to ship.</strong></div><div><strong>Engineers maintain delivery machinery.</strong></div><div><strong>Security teams chase coverage and evidence.</strong></div></div></div><div class="po-close">The same bottlenecks delay software delivery and the rollout of protection.</div>'
    for old, icon, title, detail in [('Changes wait to ship.', 'clock', 'Delayed delivery', 'Changes wait to ship.'), ('Engineers maintain delivery machinery.', 'runner', 'Engineering toil', 'Capacity goes to delivery upkeep.'), ('Security teams chase coverage and evidence.', 'approval-question', 'Slower security response', 'Required controls take longer to reach every app.')]:
        pressure['body'] = pressure['body'].replace('<div><strong>'+old+'</strong></div>', '<div>'+ico(icon)+'<span><strong>'+title+'</strong><p>'+detail+'</p></span></div>')
    pressure['body'] = f'''<div class="pv-scene">
    <svg class="pv-wires" viewBox="0 0 1280 500" aria-hidden="true"><defs><marker id="pv-tip" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="none" stroke="#a76b51" stroke-width="1.8"/></marker></defs><g fill="none" stroke="#b98268" stroke-width="3" marker-end="url(#pv-tip)"><path d="M310 105C425 105 400 230 510 230"/><path d="M310 365C425 365 400 270 510 270"/><path d="M815 250H890C925 250 925 105 960 105"/><path d="M815 250H960"/><path d="M815 250H890C925 250 925 395 960 395"/></g><path d="M450 160L605 205H775V295H605L450 340" fill="#ece1d7" stroke="#b98268" stroke-width="2"/><path d="M632 209V291M650 209V291M668 209V291" stroke="#a76b51" stroke-width="7"/><g fill="#b98268"><rect x="360" y="181" width="25" height="12" rx="3"/><rect x="400" y="212" width="25" height="12" rx="3"/><rect x="435" y="241" width="25" height="12" rx="3"/><rect x="390" y="288" width="25" height="12" rx="3"/><rect x="350" y="313" width="25" height="12" rx="3"/></g></svg>
    <div class="pv-code">{ico('code')}<h2>More code to deliver</h2><div><strong><svg viewBox="0 0 32 44" aria-hidden="true"><path d="M16 0 32 17H23V44H9V17H0Z" fill="currentColor"/></svg>98%</strong><span>more merged pull requests</span></div><div><strong><svg viewBox="0 0 32 44" aria-hidden="true"><path d="M16 0 32 17H23V44H9V17H0Z" fill="currentColor"/></svg>154%</strong><span>larger pull requests<br>on average</span></div></div>
    <div class="pv-security">{ico('approval-question')}<h2>More change to absorb</h2><p>New vulnerabilities<br>New controls and scanners</p></div>
    <div class="pv-neck"><small>THE SAME DELIVERY BOTTLENECKS</small><h2>Setup. Rollout.<br>Security evidence.</h2></div>
    <div class="pv-out pv-delay">{ico('clock')}<span><strong>Delayed delivery</strong><p>Changes wait to ship.</p></span></div>
    <div class="pv-out pv-toil">{ico('runner')}<span><strong>Engineering toil</strong><p>Capacity goes to upkeep.</p></span></div>
    <div class="pv-out pv-risk">{ico('approval-question')}<span><strong>Slower security response</strong><p>Protections take longer<br>to reach every app.</p></span></div>
    </div><div class="pv-close">The bottleneck slows both innovation and protection.</div>'''
    pressure['notes'] += ' Opening overview combines the observed Faros volume, size and review-time findings with the three enterprise pain themes developed on subsequent slides. The bottleneck diagram is the narrative interpretation, not a claim the study measured all three categories or established causation. No exponential relationship or aggregate lines-of-code multiplier is asserted.'
    research['body'] += '<p class="po-research-note">Faros 2025 also observed 91% longer review time with higher AI adoption, alongside 98% more merged pull requests and 154% larger average pull requests. This measures code-review pressure, not post-merge delivery time.</p>'
    slides.remove(pressure)
    slides.insert(1, pressure)
    return expand_comparisons(slides)

