from copy import deepcopy

def rebuild(old, ico, tool, tag, benefit):
    by={s['label']:deepcopy(s) for s in old}
    slides=[]
    def add(label,title,body,theme='',source='',notes=''):
        slides.append(dict(label=label,title=title,body=body,theme=theme,subtitle='',source=source,notes=notes))
    def keep(label):
        slides.append(by[label]);return slides[-1]
    def status(text,kind='neutral'):
        return '<span class="state '+kind+'">'+text+'</span>'
    s=keep('THE THESIS')
    s['source']='Product vision · An opinionated delivery platform for enterprise software.'
    s['notes']='Product vision; the current implementation is described in the foundation slide. No claim that full managed delivery has shipped.'
    s['body']=s['body'].replace('NO APPLICATION PIPELINES TO MAINTAIN','POLICY-DRIVEN SOFTWARE DELIVERY')

    s=keep('THE ENTERPRISE PAIN')
    s['title']='Your teams ship software.<br><em>They also maintain the machinery.</em>'
    s['body']=s['body'].replace('Developers wait','Application teams inherit delivery work').replace('Platform teams operate security plumbing','Platform teams maintain shared plumbing').replace('Security teams chase proof','Security teams reconcile the evidence')

    add('WHY NOW','AI can write the change.<br><em>Who gets it safely into production?</em>',f'''
<div class="pressure-map"><div class="change-stream"><small>CREATION IS GETTING EASIER</small><div>{ico('person')}<span>Developer changes</span></div><div>{ico('agent')}<span>Agent-generated changes</span></div><div>{ico('code')}<span>Dependency updates</span></div></div><div class="converge" aria-hidden="true"><svg viewBox="0 0 110 300" preserveAspectRatio="none"><path d="M0 45C65 45 40 150 110 150M0 150H110M0 255C65 255 40 150 110 150"/></svg></div><div class="delivery-obligations"><small>EVERY RELEASE STILL NEEDS</small><div class="obligation-grid">{''.join('<span>'+ico(i)+t+'</span>' for i,t in [('runner','Approved tools'),('package','Trusted dependencies'),('check','Tests & security checks'),('evidence','Artifact evidence'),('cloud','Infrastructure changes'),('key','Deployment authority')])}</div><div class="pressure-owner"><b>Platform + security teams</b><span>Keep this path consistent across projects, agents and environments.</span></div></div><div class="production-end">{ico('launch')}<strong>Production</strong><span>Repeatable.<br>Governed.<br>Verifiable.</span></div></div>
<div class="thesis-callout">AI makes a reliable, governed path to production more valuable.</div><div class="supporting-stat"><b>84%</b><span>of 2025 Stack Overflow survey respondents use or plan to use AI development tools.</span><small>ADOPTION CONTEXT</small></div>''',theme='pressure-slide',source='<a href="https://survey.stackoverflow.co/2025/ai">Stack Overflow Developer Survey 2025</a>. Conceptual flow; not a measured throughput or code-growth chart.',notes='The survey is adoption context, not proof of enterprise output growth or customer demand. The causal argument is the investment thesis. No queue sizes, wait times or savings are implied by the diagram.')

    add('THE COST OF FRAGMENTATION','A dependency is compromised.<br><em>What is exposed? What can ship?</em>',f'''
<div class="incident-ribbon">{ico('policy')}<b>ILLUSTRATIVE SECURITY INCIDENT</b><span>Find affected releases. Change requirements. Verify the response.</span></div>
<div class="incident-trace"><div class="trace-origin"><small>DEPENDENCY ALERT</small><h3>Package X<br>version A</h3>{status('Compromised','danger')}<p>A component now prohibited by policy.</p></div><div class="trace-arrow">→</div><div class="trace-artifact"><small>CONNECTED EVIDENCE</small><h3>payments-api · release A</h3><p>SBOM identifies the component.<br>Artifact digest links to recorded deployments.</p>{status('Affected release','danger')}<div class="deployment-chip">{tool('aws','AWS')}<span>Production deployment<br><b>Response required</b></span></div></div><div class="trace-arrow">→</div><div class="trace-decisions"><small>GOVERN WHAT HAPPENS NEXT</small><div>{status('Blocked','danger')}<span>Further promotion of the affected artifact</span></div><div>{status('Exception','warning')}<span>Explicit owner, scope and expiry</span></div><div>{status('Verified','good')}<span>A rebuilt candidate meets current requirements</span></div></div></div>
<div class="incident-payoff"><b>Fragmented delivery turns response into an investigation.</b><span>Oyzu’s target: trace exposure, apply policy, and retain proof of each decision.</span></div>''',theme='incident-slide',source='Illustrative target experience, not an actual incident or shipped dashboard. Policy changes do not patch code or remediate existing deployments.',notes='The source of exposure is a dependency-to-artifact-to-deployment relation reported by connected systems. Affected production deployments remain exposed until separately remediated. Verified means satisfying scoped policy and evidence checks, not vulnerability-free. Exceptions require explicit authorized scope; they are not automatic bypasses.')

    keep('THE OPERATING MODEL')

    add('HOW THE PLAN IS GENERATED','Change the requirements.<br><em>Oyzu derives the work.</em>',f'''
<div class="derivation-board"><div class="derivation-inputs"><div><small>APPLICATION INTENT</small><h3>Deliver payments-api<br>to staging.</h3><p>Node project + native lockfile<br>Container output · staging destination</p></div><div><small>ORGANIZATIONAL POLICY</small><h3>Use approved tools.<br>Prove release eligibility.</h3><p>Tests + security checks · SBOM<br>Signed provenance · authorized target</p></div></div><div class="compiler-line">{ico('graph')}<strong>Project facts + configuration + policy → execution plan</strong><span>No application pipeline or template.</span></div><div class="derived-actions">{''.join('<div><small>'+why+'</small><b>'+action+'</b></div>' for why,action in [('NATIVE PROJECT','Resolve tools & inputs'),('REQUIRED CHECKS','Build, test & assess'),('EVIDENCE POLICY','Generate & verify proof'),('REQUESTED OUTCOME','Publish & deliver')])}</div></div>
<div class="policy-delta"><div>{tag('NEW POLICY REQUIREMENT')}<b>Require license assessment.</b></div><span class="delta-arrow">→</span><div><b>The next plan includes the assessment and its evidence gate.</b><p>Application intent stays the same. No application pipeline edit.</p></div></div><div class="plan-foot">Generated per run. Frozen before execution. Every required action has a reason.</div>''',source='Concept storyboard; not a shipped configuration schema or managed workflow. New requirements must be supported by qualified capabilities.',notes='This illustrates the decision mechanism rather than a generic stage sequence. Runtime data binds planned artifact references; changes to outcomes require explicit replanning. Unsupported requirements fail planning rather than being silently invented. Native ecosystem adapters and platform integrations still require maintenance.')

    add('MANAGED ARTIFACT SECURITY','Proof should come with the artifact.<br><em>So should the supporting services.</em>',f'''
<div class="service-ownership"><div class="customer-estate"><small>KEEP WHAT YOU ALREADY USE</small><h3>Your projects.<br>Your execution systems.<br>Your destinations.</h3><div class="retained-tools">{tool('githubactions','Existing CI')}{tool('jfrog','Registries')}{tool('kubernetes','Delivery targets')}</div><p>Adopt Oyzu without migrating the entire tool estate.</p></div><div class="managed-estate"><small>OYZU MANAGES THE CONNECTING SERVICES · PRODUCT VISION</small><div class="service-grid">{benefit('key','Identity & signing','Coordinate authorized identities and artifact attestations.')}{benefit('evidence','Evidence & retention','Keep SBOMs, provenance and results bound to artifact digests.')}{benefit('policy','Verification & gates','Check required evidence and current authority before release.')}{benefit('clock','Audit & recovery','Record status, publication receipts, gaps and safe retries.')}</div></div></div><div class="takeaway">Less security infrastructure to assemble, integrate and operate.</div>''',source='Managed product vision. Full evidence services, publication and deployment gates are roadmap capabilities.',notes='Customer keeps CI, registries and chosen security tools. Managed services do not eliminate all customer infrastructure or security responsibilities. Signing identity, qualified producer, digest binding and fresh assessments remain distinct trust requirements. Do not imply every third-party scanner subscription is bundled.')

    keep('ONE GOVERNED DEVELOPER EXPERIENCE')

    add('THE UNIFIED AUDIT TRAIL','What was built. Why it could ship.<br><em>Where it went. One record.</em>',f'''
<div class="record-window"><div class="record-title"><div>{ico('package')}<b>payments-api / release B</b><span>Artifact detail</span></div>{tag('CONCEPT RECORD')}</div><div class="record-body"><div class="record-facts"><small>ARTIFACT IDENTITY</small><h3>One artifact.<br>Connected history.</h3><dl><dt>Source</dt><dd>Captured revision + tree</dd><dt>Toolchain</dt><dd>Runtime + builder identities</dd><dt>Policy</dt><dd>Revision + resolved decisions</dd><dt>Artifact</dt><dd>Content digest</dd></dl><div class="proof-pills"><span>SBOM</span><span>Provenance</span><span>Attestations</span></div></div><div class="record-history"><small>ACTIONS & OBSERVED STATUS · ILLUSTRATIVE</small><div class="history-event"><i></i><b>Build completed</b><span>Native commands, logs and test results retained</span>{status('Succeeded','good')}</div><div class="history-event"><i></i><b>Release eligibility checked</b><span>Required evidence verified against current policy</span>{status('Authorized','good')}</div><div class="history-event"><i></i><b>Artifact published</b><span>Destination receipt bound to the artifact digest</span>{status('Published','good')}</div><div class="history-event"><i></i><b>Staging deployment observed</b><span>Deployment event links this release to its target</span>{status('Deployed','good')}</div><div class="history-event pending"><i></i><b>Production deployment</b><span>No deployment receipt has been reported</span>{status('Not confirmed','warning')}</div></div></div></div><div class="record-bottom"><b>One record across connected build systems and deployment destinations.</b><span>Missing evidence is visible—not assumed success.</span></div>''',source='Product concept; all displayed events and states are illustrative. Full managed audit capability is roadmap.',notes='Not a screenshot of a shipped product or customer release. Status is based on observed events; lack of a receipt is not proof that no external deployment occurred. Artifact identity connects actions, attestations, provenance, publications, migrations and deployment records. The ecosystem map in the appendix preserves all requested cloud, database and infrastructure tool examples.')

    add('THE BUYER’S ALTERNATIVES','Choose who owns<br><em>the delivery machinery.</em>',f'''
<div class="choice-grid"><div class="choice"><small>BUILD & MAINTAIN INTERNALLY</small><h3>Shared workflows<br>and templates</h3><p>Reuse cuts duplication. Platform teams still own template evolution, tool integration and evidence plumbing.</p><div class="choice-example">GitHub Actions · Jenkins</div></div><div class="choice"><small>ADOPT A DELIVERY PLATFORM</small><h3>Integrated automation<br>and governance</h3><p>GitLab Auto DevOps detects projects and applies delivery templates. Harness provides delivery orchestration and governance.</p><div class="choice-example">GitLab · Harness</div></div><div class="choice oyzu-choice"><small>OYZU · PROPOSED MODEL</small><h3>Declare intent.<br>Govern through policy.</h3><p>Oyzu derives the supported work, governs tools locally and in CI, and connects evidence through delivery.</p><div class="choice-example">No application pipeline templates</div></div></div><div class="choice-tradeoff"><div><b>Compete on</b><span>Ownership of delivery logic and governance</span></div><div><b>Work together on</b><span>Existing runners, scanners and destinations</span></div><div><b>Explicit tradeoff</b><span>Opinionated support; bounded extension hooks</span></div></div>''',source='Category comparison, not a feature-exclusivity claim. Prior art and programmable-build alternatives appear in the appendix.',notes='Do not imply every incumbent lacks local tooling, policies, evidence or generated workflows. Oyzu advantage is a connected product thesis to validate. Teams still maintain intent/native config and exceptions; Oyzu maintains adapters and policy engine. Integration first does not erase direct competition for delivery/governance budget.')

    add('THE WORKING FOUNDATION','Native inputs.<br><em>Real outputs—and honest failures.</em>',f'''
<div class="foundation-demo"><div class="demo-command"><small>IMPLEMENTED CLI COMMANDS</small><code>oyzu build --plan</code><p>Inspect the captured-source plan.</p><code>oyzu build</code><p>Execute supported native build actions.</p><code>oyzu inspect dist</code><p>Check recorded content digests.</p></div><div class="demo-outcomes"><small>DOCUMENTED COMPILED-CLI LINUX CASES</small><div class="outcome-row">{ico('check')}<div><h3>Passing native test</h3><p>Vitest fixture: one passed, two skipped tests; snapshot artifact and reports retained.</p></div>{status('Artifact produced','good')}</div><div class="outcome-row">{ico('policy')}<div><h3>Failing assertion or coverage gate</h3><p>Failure reports retained. The invocation produces no artifact.</p></div>{status('No artifact','danger')}</div><div class="outcome-row">{ico('package')}<div><h3>Repeated Yarn builds</h3><p>The qualified fixture produces identical archive digests across repeated builds.</p></div>{status('Digest match','good')}</div></div></div><div class="next-foundation"><b>NEXT: THE MANAGED EXPERIENCE</b><span>Policy authority · artifact evidence services · governed publication · deployment integration</span></div>''',source='<a href="https://github.com/micahlmartin/oyzu/blob/main/docs/implementation-status.md">Implementation status, checkpoints 3, 18–19</a> · <a href="https://github.com/micahlmartin/oyzu/actions/runs/36863353630">Historical CI run 36863353630</a>. Evidence summary, not a live terminal recording.',notes='Rechecked repository documentation October 1, 2026. Command names are actual implemented CLI entry points, but toolchain images are explicitly pre-provisioned and only supported profiles qualify. No fresh execution performed for this presentation. Results reflect documented fixtures, not all projects or all platforms. inspect dist verifies bytes, not producer authentication or release eligibility. Detailed jobs and limitations are in appendix.')

    add('THE FIRST CUSTOMER','Land on a delivery mandate.<br><em>Prove value on their projects.</em>',f'''
<div class="buyer-profile"><span>BUYER</span><b>Head of Platform Engineering / DevSecOps</b><p>Multiple application teams, mixed CI systems, and recurring toolchain or security requirements.</p></div><div class="buyer-motion"><div><small>01 · REACH</small><h3>Founder-led<br>design partnerships</h3><p>Technical demonstrations and targeted outreach to platform leaders with an active mandate.</p><b>Trigger: a runtime upgrade or an evidence requirement</b></div><div><small>02 · LAND</small><h3>One supported<br>delivery path</h3><p>Use real repositories and existing CI. Baseline setup effort, policy-change work and proof retrieval.</p><b>Start with a named sponsor and acceptance criteria</b></div><div><small>03 · EXPAND</small><h3>Shared authority<br>across teams</h3><p>Extend the proven workflow to more repositories, policies and evidence-retention needs.</p><b>Purchase follows demonstrated organizational value</b></div></div>''',source='Proposed go-to-market motion; no design partners, customer commitments or commercial results are asserted.',notes='Initial customer profile is a testable hypothesis. Founder-led outreach is a proposed activity, not authorization to contact anyone from this deck task. Evaluate total customer effort, including exceptions and integration work. No use of confidential employer data or claimed endorsements.')

    add('FOUNDER FIT','Built the systems.<br><em>Understands the buyer.</em>',f'''
<div class="founder-case"><div class="founder-name"><div class="monogram">MM</div><h2>Micah Martin</h2><p class="lead">Founder · Platform engineering leader</p><p>20 years building developer infrastructure and automation.</p><p>Serial entrepreneur across startups and investments.</p></div><div class="founder-reasons"><div><small>BUILD THE PRODUCT</small><h3>Engineering and DevOps leadership</h3><p>Engineering Manager, DevOps · Lifion by ADP<br>Director of Engineering · SoulCycle</p></div><div><small>UNDERSTAND THE OPERATING REALITY</small><h3>Enterprise platform leadership</h3><p>Current AVP, Platform Engineering at a major enterprise.</p></div><div><small>EXPLAIN AND SELL THE CHANGE</small><h3>Customer-facing delivery expertise</h3><p>Solutions Architecture → Director at Harness, 2020–2024.</p></div></div></div>''',source='Role history from founder-provided LinkedIn screenshots. Career duration and entrepreneurship supplied by founder.',notes='No current employer identity, internal product name, customer results, endorsement or intellectual-property transfer claim. Listed leadership and customer-facing roles support founder fit; they are not evidence of Oyzu revenue or design partners.')

    add('THE BUSINESS MODEL','Developers adopt the experience.<br><em>Organizations buy shared control.</em>',f'''
<div class="revenue-model"><div class="free-entry"><small>ADOPTION</small><h3>Free repository-level<br>experience</h3><p>Bounded hosted policy and evidence on a supported project, using existing execution.</p><b>Prove the workflow before an organization-wide commitment.</b></div><div class="paid-core"><small>CORE RECURRING REVENUE</small><h2>Organizational governance</h2><div class="paid-features"><span>Cross-repository policy</span><span>Toolchain controls</span><span>Roles & exceptions</span><span>Credential authority</span></div><p>A shared control plane for the software delivery estate.</p><div class="revenue-expansion"><b>EXPANSION</b><span>More governed teams + evidence retention + storage usage</span></div></div></div><div class="commercial-boundary"><span><b>Existing CI first</b>Customer execution limits initial hosted compute burden.</span><span><b>Oyzu execution later</b>Optional compute adds a separate usage business.</span></div>''',source='Proposed packaging. Pricing, conversion, retention and service costs need validation; no revenue or margin forecast is asserted.',notes='This slide owns packaging, not customer acquisition. Paid organization governance is the commercial thesis. Free limits remain open. Scanning may run on customer workers; evidence storage, identity, support and service operations still cost money. Managed compute is not required to validate initial governance demand.')

    add('THE $1M SEED','Fund the managed product.<br><em>Earn repeatable paid adoption.</em>',f'''
<div class="seed-layout"><div class="seed-milestones"><small>PROPOSED 12-MONTH EXIT TARGETS</small><div><strong>3</strong><span><b>Design partners</b>Named sponsors and written acceptance criteria.</span></div><div><strong>6</strong><span><b>Independent repositories</b>Across at least two CI systems; standard onboarding ≤ 1 engineer-day per supported project.</span></div><div><strong>2</strong><span><b>Paying organizations</b>After a measured policy rollout and evidence-retrieval evaluation.</span></div></div><div class="seed-funding"><small>ILLUSTRATIVE BUDGET · $1,000,000 TOTAL</small><div class="fund-bar"><span style="width:60%"></span><span style="width:25%"></span><span style="width:15%"></span></div><div><b>$600K</b><span>Product & engineering</span></div><div><b>$250K</b><span>Customer validation & onboarding</span></div><div><b>$150K</b><span>Platform operations & reserve</span></div><p>Complete governed publication first.<br>Expand delivery integrations on the same architecture.</p></div></div><div class="seed-close">Application teams declare intent. Organizations define policy. Oyzu delivers.</div>''',theme='dark seed-slide',source='Proposed targets and illustrative 12-month plan, not commitments or a guaranteed runway. Cost assumptions and acceptance measures are in the appendix.',notes='User-specified ask: $1M. Numerical targets and budget are planning proposals, not traction, customer pipeline or approved compensation. First funded qualification ends at managed publication; complete deployment coverage and own CI extend the roadmap. Measure policy rollout against each partner baseline including exceptions, setup and infrastructure costs. Target <=8 engineer-hours onboarding per supported project with prerequisites available.')

    s=keep('BETTER TOGETHER');s['label']='APPENDIX · ECOSYSTEM';s['title']='Bring your existing tools.<br><em>Connect the delivery lifecycle.</em>'
    s['body']=s['body'].replace('Unified delivery record','Shared policy & evidence').replace('Know what was built, how, why it could ship and where it went—all in one place.','Clouds, database changes and infrastructure belong in the same governed lifecycle.')
    s=keep('TECHNICAL PROOF');s['label']='APPENDIX · ENGINEERING EVIDENCE'
    s=keep('THE BUYER’S ECONOMICS');s['label']='APPENDIX · ECONOMIC SENSITIVITY';s['notes']+=' Internal validation aid; arithmetic is not a customer ROI estimate.'

    add('APPENDIX · OPERATING PLAN','A costed planning scenario.<br><em>Explicit assumptions and exit gates.</em>',f'''
<div class="operating-grid"><div><small>ILLUSTRATIVE 12-MONTH COSTS · USD</small><table class="cost-table"><tr><td>Founder / product engineering</td><td>$120K</td></tr><tr><td>Two engineers · $180K loaded each</td><td>$360K</td></tr><tr><td>Security / integration specialists</td><td>$120K</td></tr><tr class="subtotal"><td>Product & engineering</td><td>$600K</td></tr><tr><td>Solutions / onboarding capacity</td><td>$150K</td></tr><tr><td>Partner evaluation + acquisition · $50K each</td><td>$100K</td></tr><tr><td>Cloud / evidence services</td><td>$60K</td></tr><tr><td>Legal, finance & administration</td><td>$40K</td></tr><tr><td>Reserve</td><td>$50K</td></tr><tr class="total"><td>Total planned allocation</td><td>$1M</td></tr></table></div><div class="exit-gates"><small>WHAT COUNTS AS PROGRESS</small><div><b>Qualification</b><p>Supported publication succeeds with required evidence; missing evidence blocks completion and retries preserve receipts.</p></div><div><b>Onboarding</b><p>Six independent repos across ≥2 CI systems; ≤8 engineer-hours per supported repo after prerequisites are ready.</p></div><div><b>Measured value</b><p>Compare policy-rollout labor and evidence-retrieval time against partner baselines; include exceptions and operating costs.</p></div><div><b>Commercial conversion</b><p>Two paid organizational subscriptions after an accepted evaluation; no current commitments implied.</p></div></div></div>''',source='Planning assumptions, not salary quotes or an approved hiring plan. Full allocation averages $83.3K/month; deployment timing and actual costs determine runway.',notes='Budget reconciliation: product600 + customer250 + operations150 = 1000K. Operations includes reserve50. No double count of the reserve. Founder120 + engineers360 + specialists120 = product600. Customer solutions150 + partner evaluation50 + acquisition50 =250. Operations cloud60 + administrative40 + reserve50 =150. No claimed twelve months of actual funded runway or compensation commitment.')

    add('APPENDIX · PRIOR ART','Real overlap.<br><em>A different ownership model to prove.</em>',f'''
<table class="prior-art"><thead><tr><th>Alternative</th><th>Relevant capability</th><th>Oyzu’s proposed relationship</th></tr></thead><tbody><tr><td>GitHub Actions / Jenkins</td><td>Execution and shared/reusable automation</td><td>Use their runners; derive supported application work from intent and policy.</td></tr><tr><td>GitLab Auto DevOps</td><td>Project detection and predefined build, test, security and deployment templates</td><td>Direct automation overlap; validate broader local-to-CI governance without maintaining application templates.</td></tr><tr><td>Harness</td><td>Delivery orchestration and governance</td><td>Direct budget overlap; integrate execution/delivery capabilities where useful.</td></tr><tr><td>Dagger</td><td>Portable programmable pipelines and execution graphs</td><td>Overlap in local/CI execution; Oyzu owns the opinionated generation and governance contract.</td></tr><tr><td>Cloud Native Buildpacks</td><td>Opinionated source-to-image builds and SBOM support</td><td>Overlap in native build conventions; a potential complementary build capability.</td></tr></tbody></table><div class="takeaway">Compare customer maintenance effort, enforcement coverage and exception burden—not feature checkmarks.</div>''',source='Sources in the next slide. Category-level assessment; no claim that individual capabilities are unique or absent from competitors.',notes='GitLab and Harness deliberately separated. Public evidence is documentation, not independent hands-on feature testing. Buildpacks can also centralize build upgrades and compliance. Do not imply policy generation alone is unique or that all integrations are implemented.')

    s=keep('APPENDIX · SOURCES & BOUNDARIES')
    s['body']=s['body'].replace('Concept boards and illustrative economics are labeled.','Concept boards, budget targets and illustrative economics are labeled.')
    s['source']='Sources reviewed October 1, 2026. Logos: Devicon, Simple Icons and AWS architecture assets. See bundled attribution.'
    return slides
