"""Three opening pains corresponding to the cover's three benefits."""


def frame_pains(slides, ico):
    def find(label):
        return next(s for s in slides if s['label'] == label)

    local = find('THE GOVERNANCE MULTIPLIER')
    local.update(
        label='THE DEVELOPER EXPERIENCE',
        title='Developer friction consumes<br><em>engineering capacity.</em>',
        theme='op-pain op-local op-survey',
        body='''<div class="op-survey-rows"><div class="op-survey-row"><strong class="op-row-number">67<span>%</span></strong><div><small>ENVIRONMENT READINESS</small><h2>of engineering leaders say their developers cannot build and test dev environments within <em>15 minutes.</em><sup><a href="#devex-source-1" aria-label="Source 1">1</a></sup></h2></div><p class="op-card-context">Environment setup remains a hurdle.</p></div><div class="op-survey-row"><strong class="op-row-number">50<span>%</span></strong><div><small>ORGANIZATIONAL FRICTION</small><h2>of developers report that they lose <em>10 or more hours of their time every week</em> because of organizational inefficiencies.<sup><a href="#devex-source-2" aria-label="Source 2">2</a></sup></h2></div><p class="op-card-context">Finding information. New technology. Switching between tools.</p></div></div><div class="op-centered-takeaway"><div class="op-governance-icon">''' + ico('code-alert') + '''</div><div><strong>A working setup can still be an unapproved setup.</strong><p>Developers and AI agents need approved tools, trusted sources, and company access rules. Public instructions don’t establish company approval.</p></div></div>''',

        source='<span id="devex-source-1">1. <a href="https://www.harness.io/the-state-of-software-engineering-excellence">Harness, State of Software Engineering Excellence 2025</a>: 650+ engineering leaders assessed.</span><br><span id="devex-source-2">2. <a href="https://www.atlassian.com/blog/developer/developer-experience-report-2025">Atlassian, State of Developer Experience 2025</a>: 3,500 developers and managers. Time loss includes more than environment setup.</span><br>Separate self-reported samples; not measured Oyzu savings.',
        notes='Harness 2025 report is based on 650+ engineering leaders completing the Engineering Excellence Maturity Assessment. Its developer-environments section reports that 67% say developers cannot build and test dev environments within 15 minutes. This is a reported threshold, not an average setup duration, weekly time loss or measure of corporate-policy compliance. Atlassian 2025, conducted with Wakefield Research March 13-23, surveyed 3,500 developers and managers across six countries, including 1,750 manager-level respondents. The report says 50% of developers lose 10+ hours weekly to organizational inefficiencies; this includes broader friction, not solely environment setup. Leading friction categories include finding information, new technology and switching context between tools. Do not multiply these percentages together or infer recoverable Oyzu savings. Full Atlassian report: https://dam-cdn.atl.orangelogic.com/AssetLink/5yt05dl5q8s1xljrs8747h8x6240c32p.pdf, printed pages 7-10 and methodology page 22. The governance-gap statement is product problem framing, not a survey finding about AI behavior. Public instructions may be technically correct without encoding organization-specific policy. Existing corporate controls can already address parts of this problem.',
    )
    change = find('THE ENTERPRISE PAIN')
    change.update(
        title='Every new standard becomes<br><em>another rollout project.</em>',
        theme='dark op-pain op-change',
        body='''<div class="op-rollout"><div class="op-column-head op-column-left">New enterprise requirement</div><div class="op-column-head op-column-right">Barriers to adoption</div><div class="op-requirement">''' + ico('policy') + '''<h2>Adopt a new<br>security scanner.</h2><p>One organization-wide decision.</p></div><div class="op-branches" aria-hidden="true"><svg viewBox="0 0 180 384" preserveAspectRatio="none"><path d="M24 171H104V149L156 192L104 235V213H24Z"/></svg></div><div class="op-team-obstacles"><div><span>TEAM A</span><h3>Still on the old template</h3><small>CONFIGURATION WORK</small></div><div><span>TEAM B</span><h3>Blocked by compatibility</h3><small>ADOPTION BLOCKED</small></div><div><span>TEAM C</span><h3>Waiting for rollout</h3><small>ADOPTION PENDING</small></div><div><span>TEAM D</span><h3>Operating under an exception</h3><small>COVERAGE UNRESOLVED</small></div></div></div><div class="op-rollout-takeaway"><strong>Engineering time diverted. Rollouts delayed. Control gaps persist.</strong><p>The standard changes once. The adoption work repeats across teams.</p></div>''',
        source='Illustrative adoption paths, not measured customer outcomes. Shared controls can propagate some changes centrally.',
        notes='Illustrative parallel adoption paths across four teams, not sequential steps or measured customer outcomes. One shared scanner requirement can generate configuration, compatibility, scheduling and exception work. Centralized controls can propagate some changes without repository edits. No claim that every standard requires manual changes everywhere or that policy eliminates application changes and pilot testing.',
    )
    security = find('THE COST OF FRAGMENTATION')
    security.update(
        title='A vulnerability alert becomes<br><em>an investigation.</em>',
        theme='op-pain op-security',
        body='''<div class="op-exposure"><div class="op-incident"><span class="op-alert-dot"></span><strong>Vulnerability detected</strong><span>A dependency is compromised.</span></div><h2>What is exposed <em>right now?</em></h2></div><div class="op-evidence-trail"><div class="op-evidence-object op-dependency"><div class="op-object-art">''' + ico('evidence') + '''<div class="op-record-lines"><i></i><i class="op-risk-line"></i><i></i></div><span class="op-object-tag">DEPENDENCY RECORD</span></div><h3>Which builds?</h3><p>Match the component<br>to exact artifact versions.</p></div><div class="op-evidence-gap"><span>?</span><small>MISSING LINK</small></div><div class="op-evidence-object op-artifact"><div class="op-object-art">''' + ico('package') + '''<div class="op-artifact-chips"><span>release A</span><span>release B</span></div><span class="op-object-tag">ARTIFACT REGISTRY</span></div><h3>Where deployed?</h3><p>Connect artifact digests<br>to deployment records.</p></div><div class="op-evidence-gap"><span>?</span><small>MISSING LINK</small></div><div class="op-evidence-object op-runtime"><div class="op-object-art">''' + ico('runner') + '''<div class="op-runtime-dots"><i></i><i></i><i></i><span>?</span></div><span class="op-object-tag">PRODUCTION INVENTORY</span></div><h3>Still running?</h3><p>Reconcile live state,<br>rollbacks and missing reports.</p></div></div><div class="op-exposure-impact"><strong>Slower containment. More time proving what happened.</strong><p>Disconnected records turn exposure assessment and audit proof into reconstruction work.</p></div>''',
        source='Illustrative incident. Deployment history alone does not establish current runtime state. No response-time or coverage claim.',
        notes='The pain is connecting dependencies, immutable artifacts, control evidence and observed runtime state across systems. Mature security platforms may already connect parts of this chain; no claim of universal absence or unique capability. Current exposure requires sufficiently fresh inventory, including rollbacks and out-of-band changes. Missing evidence is uncertainty, not proof of safety. The later artifact-record and managed-security slides show the intended Oyzu response. Policy changes do not remediate running applications, and delivery evidence does not guarantee compliance.',
    )
    urgency = find('WHY NOW')
    urgency.update(
        title='More changes. Bigger changes.<br><em>Longer reviews.</em>',
        theme='av-observed op-pressure',
        body='''<p class="op-pressure-intro">With higher AI adoption, teams merge more and larger changes, while reviews take longer.</p><div class="op-pressure-asymmetric"><div class="op-output-anchor"><small>MORE CHANGES</small><strong>1.98<span>×</span></strong><h2>as many merged pull requests</h2><div class="op-size-context"><small>BIGGER CHANGES</small><b>+154<span>%</span></b><p>increase in average pull-request size</p></div></div><div class="op-review-chart"><div class="op-review-total">Reviews take 91% longer</div><div class="op-review-combined"><div class="op-review-base">Baseline</div><div class="op-review-extra">Additional time</div></div><p>Compared with the same teams’ lower-adoption periods.</p></div></div><div class="op-pressure-summary"><div>AI accelerates creation.<br><strong>Delivery and governance must keep pace.</strong></div></div>''',
    )
    front = [slides[0], local, change, security, find('WHY NOW'),
             find('THE OPERATING MODEL'), find('HOW THE PLAN IS GENERATED'),
             find('THE AI OBJECTION')]
    return front + [s for s in slides if all(s is not first for first in front)]
