def update_rollout(slides):
    def find(label):return next(s for s in slides if s['label']==label)
    pain=find('THE ENTERPRISE PAIN')
    pain['body']=pain['body'].replace('Retire an<br>unsafe runtime.','Require a new<br>security scanner.').replace('Update shared templates.<br>Roll out the change.','Update shared rules or templates.<br>Coordinate adoption.').replace('RECONCILE EXCEPTIONS','UPDATE CONSUMER REFERENCES').replace('COORDINATE ADOPTION','RESOLVE EXCEPTIONS').replace('COLLECT PROOF','VERIFY ADOPTION')
    pain['notes']+=' Scanner rollout is illustrative. Centralized shared rules may propagate changes without individual repository edits; adoption and overrides depend on customer architecture.'
    local=find('ONE GOVERNED DEVELOPER EXPERIENCE')
    local['body']=local['body'].replace('One CLI and configuration interface for developers, cloud agents and existing CI.','Repositories describe the application.<br>Oyzu supplies the delivery expertise.').replace('<small>ILLUSTRATIVE TOOL REQUEST</small>','<small>AT EACH MANAGED INVOCATION</small>').replace('<span>REQUEST</span><b>Use this project’s toolchain</b>','<span>POLICY</span><b>Resolve governing policy centrally</b>').replace('<span>PREPARE</span><b>Install from a trusted source</b>','<span>PREPARE</span><b>Acquire trusted tools and inputs</b>')
    local['notes']+=' Central policy resolution can use a valid signed policy lease where permitted; offline expiration and required client capabilities must be enforced. No suggestion unrestricted network connectivity is necessary for every local action.'
    rollout=dict(label='ORGANIZATIONAL CHANGE MANAGEMENT',title='One requirement.<br><em>One governed rollout.</em>',theme='rs-rollout',subtitle='',body='''<div class="rs-example"><span>NEW STANDARD</span><b>Require a license assessment before publication.</b></div><div class="rs-stages"><div><small>01 · CAPABILITY</small><h2>Ship support.</h2><p>Release the integration through Oyzu. Identify compatible CLI versions.</p></div><div><small>02 · VALIDATION</small><h2>Pilot it.</h2><p>Test a rollout group. Surface compatibility issues and exceptions.</p></div><div><small>03 · POLICY</small><h2>Activate it.</h2><p>Set scope, approved versions, deadlines and expiring exceptions centrally.</p></div><div><small>04 · ENFORCEMENT</small><h2>Apply it.</h2><p>Compatible clients generate the required work. Older clients receive upgrade requirements.</p></div></div><div class="rs-controls"><div><small>POLICY-CONTROLLED ADOPTION</small><div class="rs-progression"><span>Notify</span><i>→</i><span>Restrict publication</span><i>→</i><b>Require upgrade</b></div><p>Platform authorization gates managed credentials and publication.</p></div><div class="rs-reach"><small>ONE MANAGED MECHANISM</small><b>Developer machines</b><b>Cloud agents</b><b>Existing CI</b></div></div><div class="rs-payoff">Roll out standards. <em>Not repository migrations.</em></div>''',source='Illustrative rollout. New capabilities require compatible clients. Application changes, pilots and authorized exceptions may still be necessary.',notes='Exact versions, approved ranges or minimum versions can be selected by organizational policy. Stage adoption using groups and deadlines; observe actual version/capability inventory, support rollback and expiring exceptions. Signed policy leases define permitted offline behavior. Client-supplied version strings alone are not trustworthy: enforcement requires appropriate identity, integrity and execution assurance at managed authority boundaries. Do not claim CLI upgrades eliminate application compatibility work. Reproducibility requires freezing and recording resolved policy, toolchain and plan identity per run; policy activation affects new decisions, not silent mutation of an executing plan. Complete lifecycle is product model; funded scope and current implementation remain on proof/ask slides.')
    slides.insert(slides.index(local)+1,rollout)
    prior=find('APPENDIX · PRIOR ART')
    prior['title']='Proven build ideas.<br><em>Central governance, built in.</em>'
    prior['theme']='rs-prior ad-appendix'
    prior['body']='''<table class="rs-table"><thead><tr><th>Foundation</th><th>What it gets right</th><th>Organizational work around it</th></tr></thead><tbody><tr><th>Bazel</th><td>Reusable rules, toolchain resolution and pinned downloads through language rules.</td><td>Distribute shared rule versions; manage adoption, exceptions and enforcement across workspaces.</td></tr><tr><th>Pants</th><td>Dependency inference, language conventions and managed tool downloads with expected digests.</td><td>Distribute approved configuration or plugins; govern overrides, client versions and adoption.</td></tr><tr><th>Buck2</th><td>Explicit toolchain dependencies, reusable rules and controlled execution mechanisms.</td><td>Supply production toolchains and coordinate shared-rule rollout across independent repositories.</td></tr></tbody></table><div class="rs-ownership"><small>OYZU MAKES THE ORGANIZATIONAL MECHANISM PART OF THE PRODUCT</small><h2>Opinionated by design. Governed centrally.</h2><p>Policy resolution · approved tools · capability rollout · exceptions · connected evidence</p><b>Application teams describe the project. Oyzu owns the supported delivery mechanics.</b></div>'''
    prior['source']='<a href="https://github.com/bazel-contrib/rules_nodejs/blob/main/nodejs/repositories.bzl">Bazel Node rules</a> · <a href="https://github.com/pantsbuild/pants/blob/main/src/python/pants/backend/javascript/subsystems/nodejs.py">Pants Node backend</a> · <a href="https://github.com/facebook/buck2/blob/main/prelude/toolchains/demo.bzl">Buck2 demo toolchains</a>. Core-project comparison; enterprise extensions and commercial services can add governance.'
    prior['notes']='Builds on established ideas, not a claim Oyzu uses these three engines as dependencies. Shared rules can propagate changes without edits to every application; monorepo and multi-repository adoption differ. Pants is already opinionated and inference-rich. These core projects do not supply the complete CLI-to-enterprise policy lifecycle described here as their standard operating model; customers and vendors can build central governance around them. No exclusivity claim. Node backend download metadata and Buck2 demo reviewed directly in source; demo is not an exhaustive inventory of Buck2 capabilities. Dagger/Buildpacks are additional prior art: portable programmable execution and source-to-image conventions respectively. Hypothesis to validate: less customer rollout/maintenance work for supported scope.'
    return slides
